### ISSUE TITLE
Any docs?

### ISSUE THREAD

**Issue by wx-Yao** [kormyen/memex#18]
Hi, thanks for building such a good tool! love the demo and the idea. But is there any doc about how to e.g., C(R)UD the snippet, how to edit tags etc? it'd be great without reading the code to get to use this thing! Appreciate it!

I had some (very basic) experience in Node but can't wrap up my mind. There's no way to do auth/login etc, i can see that. But i guess we can only edit the db file to add new knowledge snippet right?

**Comment by kormyen** [comment]
Heya!
Memex is just a simple local only thing I wrote for myself.

No real docs but there is the main read me I wrote to try to explain the basics of using memex.

Basically you just edit the data.ndtl file and run it locally.
