### ISSUE TITLE
Support tags with spaces

### ISSUE THREAD

**Issue by lcb931023** [kormyen/memex#2]
Currently the tag filtering functionality breaks when there's a space inside the tag. Would be nice to support tags with multiple words - since some concepts are difficult to condense into one English word.

Our forks have diverged by 30 something commits at this point so I'm a bit afraid to do a pull request, but here's the fix in my fork. https://github.com/dotcli/memex/commit/808df0a8e97e61c98685186c4ac9969c45bdf3a2 .

**Comment by kormyen** [comment]
Oh awesome! :D

Thanks heaps for the fix. I have manually merged it here https://github.com/kormyen/memex/commit/8b0c2cc066dafc27134d487a196ce4cf273345e2
