### ISSUE TITLE
make left sidebar scrollable

### ISSUE THREAD

**Issue by lcb931023** [kormyen/memex#3]
Currently if the sidebar overflows, the overflow part gets hidden. On smaller screens this would keep user from clicking on some of the tags.

Adding `overflow-y: scroll` to `.menu` would make this section scrollable. This means having a scroll bar between sidebar and masonry view though - not very aesthetic.

On Chrome / other Chromium based browsers, we could use `::-webkit-scrollbar` to style the scroll bar, and hide it with `display: none`. This won't work on Firefox (and probably Safari), but would work for the Electron build too.

If we want it to be scrollable and aesthetic - like Slack's sidebar scroller, for example - a 3rd party javascript library will have to be used :<

Here's the commit in my fork, for reference: https://github.com/dotcli/memex/commit/1020238c66212406bce2714129ce0f5e4ba523bd

**Comment by kormyen** [comment]
Cheers!

I manually merged your fix here: https://github.com/kormyen/memex/commit/4e0771c64e363ac55540d7d6486b34063bbf4621

I had a quick look for options for styling (or hiding) the scrollbar in Firefox and didn't find anything ideal. Can worry about it later.
